jwt:
  secret: 413F44284728486250655368566D5970337336763979244226452948404D6351
  lifetime: 86400s

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:test_db}
    username: ${DB_USER:testuser}
    password: ${DB_PASS:testpas}
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
  main:
    allow-circular-references: true

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

minio:
  bucket: ${MINIO_BUCKET:images}
  url: ${MINIO_URL:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}

